name: PHT
channels:
  - free
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _openmp_mutex=4.5
  - altair=5.0.1
  - anyio=4.7.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - boost-cpp=1.84.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - contourpy=1.2.0
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gts=0.7.6
  - h11=0.14.0
  - harfbuzz=4.3.0
  - httpcore=1.0.2
  - httpx=0.28.1
  - icu=73.2
  - idna=3.7
  - imageio=2.33.1
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.43
  - lerc=3.0
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-devel=1.84.0
  - libboost-headers=1.84.0
  - libboost-python=1.84.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=3.0.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.78.4
  - libhwloc=2.9.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libpng=1.6.39
  - libpq=12.20
  - libsodium=1.0.18
  - libsqlite=3.41.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libzlib=1.2.13
  - llvm-openmp=20.1.4
  - lz4-c=1.9.4
  - mako=1.3.6
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpi=1.0
  - mpi4py=3.1.4
  - munkres=1.1.4
  - mysql=5.7.20
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.89.1
  - numexpr=2.10.1
  - openjpeg=2.5.2
  - openmpi=4.1.6
  - openssl=3.4.0
  - overrides=7.4.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pillow=11.0.0
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=5.24.1
  - ply=3.11
  - poppler=24.09.0
  - poppler-data=0.4.11
  - prometheus_client=0.21.1
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pycuda=2024.1
  - pympler=0.9
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytools=2024.1.6
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.2
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - tinycss2=1.4.0
  - tk=8.6.12
  - tomli=2.2.1
  - toolz=0.12.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - asttokens==2.4.1
      - colorama==0.4.6
      - comm==0.2.2
      - dataclasses-json==0.6.7
      - deprecated==1.2.15
      - executing==2.1.0
      - filelock==3.18.0
      - freetype-py==2.5.1
      - gower==0.1.2
      - graphviz==0.20.3
      - hsluv==5.0.4
      - igraph==0.11.2
      - iniconfig==2.0.0
      - ipydatawidgets==4.3.5
      - ipython==8.29.0
      - ipywidgets==8.1.5
      - joblib==1.3.2
      - jupyterlab-widgets==3.0.13
      - liac-arff==2.5.0
      - marshmallow==3.23.1
      - matplotlib-inline==0.1.7
      - mypy-extensions==1.0.0
      - numpy==1.26.1
      - packaging==23.2
      - patsy==0.5.3
      - pexpect==4.9.0
      - pip==24.3.1
      - pluggy==1.3.0
      - prompt-toolkit==3.0.48
      - pure-eval==0.2.3
      - pygame==2.6.1
      - pygltflib==1.16.2
      - pygments==2.18.0
      - pymfe==0.4.2
      - pyopengl==3.1.7
      - pyopengl-accelerate==3.1.7
      - pytest==7.4.3
      - python-dateutil==2.8.2
      - pythreejs==2.4.2
      - pytz==2023.3.post1
      - river==0.22.0
      - scikit-learn==1.3.2
      - setuptools==75.6.0
      - stack-data==0.6.3
      - statsmodels==0.14.0
      - tabulate==0.9.0
      - texttable==1.7.0
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - traittypes==0.2.1
      - typing-inspect==0.9.0
      - vispy==0.14.3
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.13
      - wrapt==1.17.0
